# Generated by Django 3.2.3 on 2021-06-03 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='last_complete',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
